apiVersion: v1
kind: Service
metadata:
  name: nodeinfo
  namespace: demo
  labels:
    app: nodeinfo
spec:
  type: ClusterIP
  selector:
    app: nodeinfo
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
